spring:
  application:
    name: AiDevs
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
    vectorstore:
      qdrant:
        collection-name: ai_devs
tasks:
  baseUrl: ${AIDEVS_TASKS_URL}
  apiKey: ${AIDEVS_API_KEY}
render_forn:
  apiKey: ${RENDER_FORM_API_KEY}
